# Generated by Django 6.0 on 2026-07-22 05:26

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('match_name', models.CharField(max_length=200, verbose_name='Match Name')),
                ('num_tickets', models.IntegerField(verbose_name='Number of Tickets')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount (₹)')),
                ('order_id', models.CharField(default=payments.models.generate_order_id, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Booking Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'IPL Ticket Booking',
                'verbose_name_plural': 'IPL Ticket Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('food_name', models.CharField(max_length=200, verbose_name='Food Item')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price per Item (₹)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount (₹)')),
                ('order_id', models.CharField(default=payments.models.generate_order_id, max_length=50, unique=True)),
                ('stripe_session_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stripe Session ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Food Order (Stripe)',
                'verbose_name_plural': 'Food Orders (Stripe)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('order_id', models.CharField(max_length=50, verbose_name='Order ID')),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gateway Transaction ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (₹)')),
                ('gateway', models.CharField(choices=[('PAYTM', 'Paytm'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal')], max_length=20, verbose_name='Payment Gateway')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20, verbose_name='Payment Status')),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Mode')),
                ('raw_response', models.TextField(blank=True, null=True, verbose_name='Raw Gateway Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Payment Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
