# Write a Python program to access values between index 1 and 5 in a tuple.
tuple = (10, 20, 30, 40, 50, 60)
print(tuple[1:6])

#  Write a Python program to access alternate values between index 1 and 5 in a tuple
tuple = (10, 20, 30, 40, 50, 60)
print(tuple[1:6:2])


#----------------------------------Practical Examples-------------------------------------#

#  11) Write a Python program to access values between index 1 and 5 in a tuple. 
tuple = (10, 20, 30, 40, 50, 60)
print(tuple[1:6])

# 12) Write a Python program to access the value from the last index in a tuple
tuple = (10, 20, 30, 40, 50)
print(tuple[-1])