# Write a Python program to create a dictionary with 6 key-value pairs.
dict = {
    "name": "Aayushi",
    "age": 20,
    "city": "Rajkot",
    "course": "Python",
    "marks": 85,
    "grade": "A"
}
print(dict)

# Write a Python program to access values using dictionary keys
dict = {
    "name": "Aayushi",  
    "age": 20,
    "city": "Rajkot",
    "course": "Python",
    "marks": 85,
    "grade": "A"
}
print("Name:", dict["name"])
print("Age:", dict["age"])
print("City:", dict["city"])
print("Course:", dict["course"])
print("Marks:", dict["marks"])
print("Grade:", dict["grade"])


#----------------------------------Practical Examples-------------------------------------#

#13) Write a Python program to create a dictionary of 6 key-value pairs
dict = {
    "name": "Ayu",
    "age": 16,
    "city": "jjp",
    "course": "Python",
    "marks": 95,
    "grade": "A+"
}
print(dict)

# 14) Write a Python program to access values using keys from a dictionary
dict = {
    "name": "Ayu",  
    "age": 16,
    "city": "jjp",
    "course": "Python",
    "marks": 95,
    "grade": "A+"
}
print("Name:", dict["name"])
print("Age:", dict["age"])
print("City:", dict["city"])
print("Course:", dict["course"])
print("Marks:", dict["marks"])
print("Grade:", dict["grade"])
